#pragma once
#include <3ds.h>
#include <spritetools.h>
#include <stdio.h>
enum Sprites
{
	WATER_1 = 0,
	WATER_3,
	WATER_2,
	WATER_4,
	MINE_OFF,
	MINE_ON,
	WALL,
	ROCK,
	PLAYER_UP_STAND,
	PLAYER_UP_WALK_2,
	PLAYER_UP_WALK_1,
	PLAYER_RIGHT_WALK_1,
	PLAYER_RIGHT_STAND,
	PLAYER_RIGHT_WALK_2,
	PLAYER_LEFT_STAND,
	PLAYER_LEFT_WALK_2,
	PLAYER_LEFT_WALK_1,
	PLAYER_DOWN_WALK_1,
	PLAYER_DOWN_STAND,
	PLAYER_DOWN_WALK_2
};
